apiVersion: v1
kind: Pod
metadata:
  name: my-secret-pod
spec:
  containers:
  - name: myapp
    image: busybox
    command: ["sleep", "3600"]
    env:
    - name: DB_PASSWORD
      valueFrom:
        secretKeyRef:
          name: my-db-secret
          key: db-password.txt
    volumeMounts:
    - name: secret-volume
      mountPath: /app/secrets
  volumes:
  - name: secret-volume
    secret:
      secretName: my-db-secret
