apiVersion: v1
kind: Pod
metadata:
  name: my-config-pod
spec:
  containers:
  - name: myapp
    image: busybox
    command: ["sleep", "3600"]
    volumeMounts:
    - name: config-volume
      mountPath: /app/config
  volumes:
  - name: config-volume
    configMap:
      name: my-config-file
