apiVersion: v1
kind: Secret

metadata:
  name: postgres-secret

  namespace: default
type: Opaque
stringData:

  POSTGRES_PASSWORD: "Krishna1899!!"
  POSTGRES_USER: "devopsuser"

  POSTGRES_DB: "devopsdb"

